=== rocx320/lab3/lab3.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="freelance">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="freelancer">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="id" type="xs:unsignedInt" />
                            <xs:element name="contact">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="email" type="xs:string" />
                                        <xs:element name="phone"    >
                                            <xs:simpleType>
                                        <xs:restriction base = "xs:integer">
                                            <xs:pattern value = "[0-9]{10}"/>
                                        </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="work">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="portfolio" type="xs:string" />
                                        <xs:element name="review" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rocx320/lab3/Lab3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="lab3-style.xsl" type="text/xsl"?>
<freelance xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lab3.xsd">
 
    <freelancer>
        <name>Hemant Dutta</name>
        <id>2247216</id>
        <contact>
            <email>hemantdutta123@gmail.com</email>
            <phone>9988833112</phone>
        </contact>
        <work>
            <portfolio>Web Dev</portfolio>
            <review>5 Stars</review>
        </work>
    </freelancer>

    <freelancer>
        <name>Siddharth Raj</name>
        <id>2247234</id>
        <contact>
            <email>siddharthraj123@gmail.com</email>
            <phone>9988833113</phone>
        </contact>
        <work>
            <portfolio>Data Engg</portfolio>
            <review>5 Stars</review>
        </work>
    </freelancer>

    <freelancer>
        <name>Sarthak Mathur</name>
        <id>2247262</id>
        <contact>
            <email>sarthakmathur123@gmail.com</email>
            <phone>9988833110</phone>
        </contact>
        <work>
            <portfolio>Java Dev</portfolio>
            <review>5 Stars</review>
        </work>
    </freelancer>

    <freelancer>
        <name>Rohan Shaw</name>
        <id>2247231</id>
        <contact>
            <email>rohanshaw123@gmail.com</email>
            <phone>9988833111</phone>
        </contact>
        <work>
            <portfolio>AI</portfolio>
            <review>5 Stars</review>
        </work>
    </freelancer>
</freelance>
